Writer.create(name: "Jim Smith")
Writer.create(name: "Bill Jones")
Writer.create(name: "Todd James")
Writer.create(name: "Jackson Dortz")
Writer.create(name: "Fred Flintz")
Writer.create(name: "Samuel Axe")

Call.create(title: "Feathers of Passion", theme: "Love")
Call.create(title: "Necro Heights", theme: "Fear")
Call.create(title: "Regul8t0r", theme: "Justice")
Call.create(title: "Otter Truth", theme: "Nature")
Call.create(title: "People Places", theme: "Society")
Call.create(title: "Adrenaline Via Fright", theme: "Fear")
Call.create(title: "Truth as Fiction", theme: "Justice")
Call.create(title: "Laser Whales", theme: "Nature")
Call.create(title: "Brave & New", theme: "Society")
Call.create(title: "Fast Pulses", theme: "Love")
