Writer.create(name: "Hunter S. Thompson")
Writer.create(name: "Mark Twain")
Writer.create(name: "William Burroughs")
Writer.create(name: "Frank Dune")

Call.create(title: "Feathers of Passion", theme: "Romance")
Call.create(title: "Necromania Heights", theme: "Fear")
Call.create(title: "Regulation Nation", theme: "Society")
Call.create(title: "The Otter Truth", theme: "Nature")


Application.create(title: "Test Peom", body: "Today a poem tomorrow a haiku", writer_id: 1, call_id: 1)
Application.create(title: "Trouble Everyday", body: "Words reach you while your thoughts travelh through time.", writer_id: 2, call_id: 1)
Application.create(title: "Pizza Rat", body: "A rat, a pizza slice, stairs... life.", writer_id: 3, call_id: 1)
Application.create(title: "Snow is blind", body: "When snow comes, knows not where it goes", writer_id: 4, call_id: 1)
Application.create(title: "Boat", body: "Boats, like cars but in water, take you away", writer_id: 1, call_id: 2)
Application.create(title: "Fig Tree", body: "Your jams help me pass the time", writer_id: 2, call_id: 2)
Application.create(title: "Law", body: "Rules are meant to be mended", writer_id: 3, call_id: 2)
Application.create(title: "Blood Ocean", body: "I know who you are!", writer_id: 4, call_id: 2)
Application.create(title: "Fountains", body: "Small volcanoes, angry with water", writer_id: 1, call_id: 3)
Application.create(title: "BPM", body: "My races while you move in places", writer_id: 2, call_id: 3)
